---
title: Cezar Leahu
email: cezar.leahu@protonmail.com
description: >-
  Iasi, Romania <br/>
  cezar.leahu@protonmail.com <br/>

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  CezarLeahu

# Build settings
#theme: minima
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

#logo: [Location of the logo]
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
